development: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  database: assetbundle
  socket: /uca/var/mysql/mysql.sock
production: 
  <<: *default
  host: <%= ENV['RAILS_DB_HOST'] %>
  username: <%= ENV['RAILS_DB_USER'] %>
  password: <%= ENV['RAILS_DB_PASS'] %>
  database: <%= ENV['RAILS_DB_NAME'] %>
